---
# tasks file for pull-pkgs
- name: mkdir  pkg-dir
  file:
    path: "{{ pkg_dir }}"
    state: directory

- name: Install podman on localhost
  yum:
    name: podman
    state: latest

- name: Pull the pkg container image
  podman_image:
    name: "{{ image_name }}"

- name: Check if {{ container_name }} container already exists
  shell: podman ps -a | grep {{ container_name }} | wc -l
  register: ctr_count

- debug:
    var: ctr_count.stdout

- name: Remove {{ container_name }} container
  shell: podman rm "{{ container_name }}" -f 
  when: ctr_count.stdout == "1"

- name: Run pkg container
  shell: podman run --name "{{ container_name }}" -d "{{ image_name }}"

- name: Copy all the packages from pkg container
  shell: podman cp "{{ container_name }}":/root/{{ item }} "{{ pkg_dir }}"
  loop: "{{ packages }}"

- name: Stop and remove {{ container_name }} container
  shell: podman rm -f "{{ container_name }}"
