---
# tasks file for pull-pkgs
- name: mkdir  pkg-dir
  file:
    path: "{{ pkg_dir }}"
    state: directory

- name: Install podman on localhost
  yum:
    name: podman
    state: latest

- name: Pull the pkg container image
  podman_image:
    name: "{{ image_name }}"

- name: Kill {{ container_name }} container
  shell: podman kill "{{ container_name }}"

- name: Remove {{ container_name }} container
  shell: podman rm "{{ container_name }}" -f 

- name: Run pkg container
  shell: podman run --name "{{ container_name }}" -d "{{ image_name }}"

- name: Copy all the packages from pkg container
  shell: podman cp "{{ container_name }}":/root/{{ item }} "{{ pkg_dir }}"
  loop: "{{ packages }}"
