---
- name: Pull required packages
  hosts: all
  roles:
    - sysinit

- name: Init kubernetes cluster
  hosts: master[0]
  roles:
    - k8sinit

- name: Join other two masters
  hosts: master[1:]
  roles:
    - joinmaster

- name: Join workers
  hosts: worker
  roles:
    - joinworker
