---
- name: Pull required packages
  hosts: master
  roles:
    - sysinit

- name: Init kubernetes cluster
  hosts: master[0]
  roles:
    - k8sinit

      #- name: Join other two masters
      #  hosts: master[1,2]
      #  roles:
      #    - joinmaster
