---
- name: Pull required packages
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - pull-pkgs

- name: Initialize all target hosts
  hosts: all
  gather_facts: no
  roles:
    - sysinit

- name: Deploy a fully functional kubernetes cluster
  hosts: all
  remote_user: root
  gather_facts: no
  roles:
    - k8s
