---
- name: Pull required packages
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - pull-pkgs

- name: Initialize all target hosts
  hosts: all
  gather_facts: no
  roles:
    - sysinit

- name: Deploy a fully functional kubernetes cluster
  hosts: master[0]
  remote_user: root
  gather_facts: no
  tasks:

    - import_role:
        name: k8s
      tags: master0
