---
- name: Generate hosts file
  hosts: all
  tasks:
    - name: var test
      debug:
        msg: this is {{ inventory_hostname }}

    - debug:
        msg: All hosts are {{ ansible_play_hosts_all }}

    - debug:
        msg: All hosts are {{ ansible_host }}
    - template:
        src: nametest.j2
        dest: /tmp/hosts

    - shell: cat /tmp/hosts
      register: hoststest

    - debug:
        var: hoststest
