---
# tasks file for sysinit
- name: Make sure br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: Setup netfilter
  copy:
    content: br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    force: true

- name: Setup kernel param
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1  
    dest: /etc/sysctl.d/k8s.conf
    force: true

- name: Run sysctl
  shell: sysctl --system

- name: Disable SELINUX
  selinux:
    state: disabled

- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Copy deps pkgs to all hosts
  copy:
    src: /tmp/{{ item }}
    dest: /tmp
  loop: "{{ pkg_src }}"

- name: Unarchive crio pkg
  unarchive:
    src: /tmp/{{ crio_pkg }}
    dest: /tmp
    remote_src: yes

- name: Install crio
  shell: /tmp/cri-o/install

- name: Unarchive kubeadm kubectl kubelet
  unarchive:
    src: /tmp/{{ item }}
    dest: /usr/bin
    remote_src: yes
  loop:
    - kubeadm.tar.xz
    - kubectl.tar.xz
    - kubelet.tar.xz
