---
# tasks file for sysinit
- name: Set up host name
  template:
    src: hostname.j2
    dest: /etc/hostname
    force: yes

- name: Install hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    force: yes

- name: Make sure br_netfilter module is loaded after reboot
  copy:
    content: br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    force: yes

- name: Disable SELINUX
  selinux:
    state: disabled

- name: Reboot machines
  reboot: 
    
- name: Setup kernel param
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Copy deps pkgs to all hosts
  copy:
    src: /tmp/{{ item }}
    dest: /tmp
  loop: "{{ pkg_src }}"

- name: Unarchive crio pkg
  unarchive:
    src: /tmp/{{ crio_pkg }}
    dest: /tmp
    remote_src: yes

- name: Install crio
  shell: ./install
  args:
    chdir: /tmp/cri-o

- name: Daemon reload
  systemd:
    daemon_reload: yes

- name: Enable and start cri-o service
  service:
    name: crio
    state: started
    enabled: yes

- name: Unarchive kubeadm kubectl kubelet
  unarchive:
    src: /tmp/{{ item }}
    dest: /usr/bin
    remote_src: yes
  loop:
    - kubeadm.tar.xz
    - kubectl.tar.xz
    - kubelet.tar.xz

- name: Install kubelet.service
  copy:
    src: kubelet.service
    dest: /usr/lib/systemd/system

- name: Ensure kubelet.d dir exists
  file:
    path: "{{ kubelet_svc_dir }}"
    state: directory

- name: Install kubeadm.conf
  copy:
    src: 10-kubeadm.conf
    dest: "{{ kubelet_svc_dir }}"

- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Enable and start kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes
