---
# tasks file for sysinit
- name: Make sure br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: Setup netfilter
  copy:
    content: br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    force: true

- name: Setup kernel param
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1  
    dest: /etc/sysctl.d/k8s.conf
    force: true

- name: Run sysctl
  shell: sysctl --system

- name: Disable SELINUX
  selinux:
    state: disabled

- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Copy docker-ce repo to all hosts
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/
    force: yes

- name: Install docker on all hosts
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
