---
# tasks file for k8s
- name: Install kubeadm kubectl kubelet on master
  copy: 
    src: "{{ item }}"
    dest: /tmp
    force: yes
  loop: 
    - kubeadm.tar.xz
    - kubectl.tar.xz
    - kubelet.tar.xz

- name: Unarchive the packages
  unarchive:
    src: "{{ item }}"
    dest: /usr/bin
    remote_src: yes
  loop:
    - /tmp/kubeadm.tar.xz
    - /tmp/kubectl.tar.xz
    - /tmp/kubelet.tar.xz

- name: Chage mode on cmd
  file:
    path: "{{ item }}"
    state: file
    mode: 0755
  loop:
    - /usr/bin/kubeadm
    - /usr/bin/kubectl
    - /usr/bin/kubelet

- name: Install kubelet.service file 
  copy:
    src: kubelet.service
    dest: /usr/lib/systemd/system
    force: yes

- name: Reload daemon
  shell:
    cmd: systemctl daemon-reload

- name: Enable and start kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Configure cmd auto completion
  blockinfile:
    path: /root/.bash_profile
    block: |
      source <(kubeadm completion bash)
      source <(kubectl completion bash)
