---
# tasks file for k8s
- name: Pull kubernetes container images
  shell: kubeadm config images pull --image-repository {{ my_registry }} --kubernetes-version {{ kubernetes_version }}
  register: kubeadm_image_pull
  tags: master0

- debug: 
    var: kubeadm_image_pull.stdout_lines
  tags: master0

- name: Init first master
  shell: kubeadm init --upload-certs --image-repository {{ my_registry }} --kubernetes-version {{ kubernetes_version }} --pod-network-cidr {{ pod_network_cidr }} --apiserver-advertise-address {{ ansible_facts['default_ipv4']['address'] }} --control-plane-endpoint {{ ansible_facts['hostname'] }} | tee /tmp/kubeadm-init.txt
  register: kubeadm_init
  tags: master0

- name: Make kubeconfig dir
  file: 
    path: "{{ kubeconfig_dir }}"
    state: directory

- name: Install kubeconfig file
  shell: cp -f {{ kubeadmin_file }} {{ kubeconfig_dir }}/config

- debug:
    var: kubeadm_init
  tags: master0

- name: Generate join command for other masters
  shell: grep 'kubeadm join' /tmp/kubeadm-init.txt -A 3 | head -3 > /tmp/join_master.sh
  tags: master0

- name: Generate join command for workers
  shell: grep 'kubeadm join' /tmp/kubeadm-init.txt -A 3 | tail -2 > /tmp/join_worker.sh
  tags: master0

- name: Fetch join command file
  fetch:
    src: "{{ item }}"
    dest: /tmp/
    flat: yes
  loop: 
    - /tmp/join_master.sh
    - /tmp/join_worker.sh
  tags: master0

- name: Fetch hosts file 
  fetch:
    src: /etc/hosts
    dest: /tmp/
    flat: yes
  tags: master0

- name: Install hosts file
  copy:
    src: /tmp/hosts
    dest: /etc/hosts
    force: yes
  tags:
    - join_master
    - join_worker

- name: Install join file to other control-plane machines
  copy:
    src: /tmp/join_master.sh
    dest: /tmp/
    force: yes
  tags: join_master

- name: Join other control-plane machines to the cluster
  shell: bash /tmp/join_master.sh | tee /tmp/join_master.log
  register: join_master
  tags: join-master

- debug:
    var: join-master
  tags: join_master

- name: Install join file to worker nodes
  copy:
    src: /tmp/join_worker.sh
    dest: /tmp/
    force: yes
  tags: join_worker

- name: Join worker nodes to the cluster
  shell: bash /tmp/join_worker.sh | tee /tmp/join_worker.log
  register: join_worker
  tags: join_worker

- debug:
    var: join_worker
  tags: join_worker

- name: Install calico crd yaml file
  copy:
    src: tigera-operator.yaml
    dest: /tmp/
    force: yes
  tags: master0

- name: Install calico cr yaml file
  template:
    src: custom-resources.j2
    dest: /tmp/custom-resources.yaml
    force: yes
  tags: master0

- name: Install calico
  shell: kubectl apply -f /tmp/tigera-operator.yaml -f /tmp/custom-resources.yaml
  register: install_calico
  tags: master0

- debug:
    var: install_calico
  tags: master0
